/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#474746",
        "primary": "#000000",
        "surface-container-high": "#eae7e7",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#3e4c16",
        "on-primary-fixed": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "tertiary-container": "#161f00",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c1c",
        "inverse-on-surface": "#f3f0f0",
        "background": "#fcf9f8",
        "inverse-primary": "#c8c6c5",
        "primary-container": "#1c1b1b",
        "on-tertiary-fixed": "#161f00",
        "secondary-fixed-dim": "#c8c6c2",
        "secondary-fixed": "#e4e2dd",
        "on-secondary-fixed-variant": "#474744",
        "tertiary-fixed": "#d9eaa3",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e4e2e1",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#bdce89",
        "surface-variant": "#e4e2e1",
        "error": "#ba1a1a",
        "surface-bright": "#fcf9f8",
        "on-primary-container": "#858383",
        "secondary": "#5e5e5b",
        "outline-variant": "#c4c7c7",
        "on-secondary-fixed": "#1b1c19",
        "outline": "#747878",
        "tertiary": "#000000",
        "surface": "#fcf9f8",
        "on-background": "#1b1c1c",
        "on-surface-variant": "#444748",
        "surface-container": "#f0eded",
        "primary-fixed": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7b8a4d",
        "inverse-surface": "#303030",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container-low": "#f6f3f2",
        "on-secondary-container": "#63635f",
        "secondary-container": "#e1dfdb",
        "surface-tint": "#5f5e5e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "none": "0px",
        "sm": "0.125rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "120px",
        "margin-mobile": "20px",
        "unit": "4px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "data-num": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-xl": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "data-num": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-xl": ["80px", { lineHeight: "90px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
